### ISSUE TITLE
Where is the Text comming from?

### ISSUE THREAD

**Issue by JPe2** [athombv/homey-rfdriver-examples#1]
@BasKiers 
Hi, I'm working on translating the Brel App to Forest-TCS curtains
![image](https://user-images.githubusercontent.com/3833862/40238499-a1e854d8-5ab3-11e8-8096-af7ff609ffd7.png)

I like to know where the texts "Omhoog" , "Omlaag" and "Stil" are located, I need to change them into "Openen" , "Sluiten" and "Stop"  for my curtains.

![image](https://user-images.githubusercontent.com/3833862/40238752-68d7f4f4-5ab4-11e8-96af-3787fc9d9080.png)
The text representing the device Name is partly covered. How can this be changed?

**Comment by jeroenvollenbrock** [comment]
@JPe2 The translations and of those strings are managed by homey itself, as the flow card is generated by a system capability. You probably have to change the device class to curtains instead of window coverings.

**Comment by JPe2** [comment]
image
The text representing the device Name is partly covered. How can this be changed?
